<html><head></head><body>import DefaultLayout from '@/components/Layouts/DefaultLayout';

export default function ck_incubatorPage() {
 return (<defaultlayout><div classname="container mx-auto px-4 py-8"><h1 classname="text-3xl font-bold mb-4">ck incubator</h1><div dangerouslysetinnerhtml="{{" __html:="" `<img="" width="300" height="300" src="https://fitterlaw.com/wp-content/uploads/2020/11/Fitter-Law-Circle-Logo-01-300x300.png" alt="Fitter Law, LLC" loading="lazy" srcset="https://i2.wp.com/fitterlaw.com/wp-content/uploads/2020/11/Fitter-Law-Circle-Logo-01.png?resize=300%2C300&amp;ssl=1 300w, https://i2.wp.com/fitterlaw.com/wp-content/uploads/2020/11/Fitter-Law-Circle-Logo-01.png?resize=1024%2C1024&amp;ssl=1 1024w, https://i2.wp.com/fitterlaw.com/wp-content/uploads/2020/11/Fitter-Law-Circle-Logo-01.png?resize=150%2C150&amp;ssl=1 150w, https://i2.wp.com/fitterlaw.com/wp-content/uploads/2020/11/Fitter-Law-Circle-Logo-01.png?resize=768%2C768&amp;ssl=1 768w, https://i2.wp.com/fitterlaw.com/wp-content/uploads/2020/11/Fitter-Law-Circle-Logo-01.png?resize=1536%2C1536&amp;ssl=1 1536w, https://i2.wp.com/fitterlaw.com/wp-content/uploads/2020/11/Fitter-Law-Circle-Logo-01.png?resize=2048%2C2048&amp;ssl=1 2048w, https://i2.wp.com/fitterlaw.com/wp-content/uploads/2020/11/Fitter-Law-Circle-Logo-01.png?resize=80%2C80&amp;ssl=1 80w, https://i2.wp.com/fitterlaw.com/wp-content/uploads/2020/11/Fitter-Law-Circle-Logo-01.png?resize=1170%2C1170&amp;ssl=1 1170w, https://i2.wp.com/fitterlaw.com/wp-content/uploads/2020/11/Fitter-Law-Circle-Logo-01.png?w=2232&amp;ssl=1 2232w" sizes="(max-width: 300px) 100vw, 300px"><h3>AND</h3><img width="300" height="81" src="https://fitterlaw.com/wp-content/uploads/2021/01/KENT_horiz_lockup-300x81.jpg" alt="" loading="lazy" srcset="https://i1.wp.com/fitterlaw.com/wp-content/uploads/2021/01/KENT_horiz_lockup.jpg?resize=300%2C81&amp;ssl=1 300w, https://i1.wp.com/fitterlaw.com/wp-content/uploads/2021/01/KENT_horiz_lockup.jpg?resize=768%2C208&amp;ssl=1 768w, https://i1.wp.com/fitterlaw.com/wp-content/uploads/2021/01/KENT_horiz_lockup.jpg?w=863&amp;ssl=1 863w" sizes="(max-width: 300px) 100vw, 300px"><h3></h3><h3>SSPI
INCUBATOR</h3>LEGAL

SUBSCRIPTION<ul><li><b><u>UNLIMITED</u></b>Legal Consultations</li><li><b><u>UNLIMITED</u></b>Business Consultations</li><li><b><u>UNLIMITED</u></b>Document Reviews</li><li><b><u>FLAT-FEE</u></b>Custom Contract Drafting<b>+</b></li><li><b><u>UNLIMITED</u></b>Business Consultations</li><li>Access to<b><u>Attorney Network</u></b></li><li>Registered Agent Services<b>*</b></li><li>Access to<u><b>Litigation Services**</b></u></li><li>Intellectual Property Services</li><li>Access to Additional Software</li><li>ERISA Matters</li><li>and Much More...</li></ul><a href="https://fitterlaw.com?ff_landing=14">Apply Now</a>University Programs, Incubators, Accelerators, Private Equity, Venture Capital, Start-ups seeking funding
CK IIT SSPI<h4>FAQ</h4><h4>Are you a law firm?</h4>Yes, we are a law firm, headquartered in Chicago, licensed to practice in Illinois and on Federal matters.<h4>How many subscribers do you normally accept?</h4>We don't have a set number.&nbsp; We are more interested in understanding your business and how we can help you.&nbsp; We tend to decline applications that don't get us excited within the first few lines of the description (so be sure to be thorough and exciting!).<h4>Do I have to sign a contract?</h4>No, we simply bill you monthly.&nbsp; If you ever decide to cancel (which we doubt) your subscription will simply end at the end of that billing cycle.<h4>Do you offer refunds?</h4>We generally don't offer refunds, except in limited circumstances, at our discretion, and if we deny your initial application.<h4>What makes you different from the other prepaid legal plans?</h4>Fitter Law's subscription program is not a pre-paid legal plan.&nbsp; The subscription fee is to retain us for our availability throughout the month.<h4>Are there any other fees?</h4>Yes, for any additional services that we provide, we will quote you a fee for the service.&nbsp; This fee will be either a flat-fee, hourly, contingency, or blended.&nbsp; We do most of our work on flat-fee or blended fee basis (reduced up-front + contingency).<h4>How do I use my unlimited consultations?</h4>You will be given access to various firm calendars and you can select a time for us to call you directly.&nbsp; It's that simple.<h4>Why Do I have to pay Now?</h4>Except in the case of nonprofits with limited budgets, a $500 fee is charged for the initial client consultation.<h4>Can anyone become a subscriber?</h4>The SSPI Incubator Legal Services Subscription Program is only available to startups and businesses that come through the Chicago-Kent College of Law, Illinois Institute of Technology Small and Solo Practice Incubator.<h4>What happens after I submit the application?</h4>One of our team members will review your application and verify the information.&nbsp; We also perform a conflicts check on every new client.<h4>Do you litigate?</h4>We take on both, transactional and litigation matters, either directly or we may choose to work with another law firm.<h4>What happens if my application is declined?</h4>We will email you and may choose to give you an opportunity to respond.<hr>+ Fitter Law will provide lifetime pre-litigation contract protection for any contract that we draft, as long as you stay a subscriber of the firm without any gaps in subscription.&nbsp; See<a href="https://fitterlaw.com/terms-of-service/" target="_blank" rel="noopener">Terms &amp; Conditions</a>for additional details.

* Client is responsible for all government fees.&nbsp; &nbsp;See<a href="https://fitterlaw.com/terms-of-service/" target="_blank" rel="noopener">Terms &amp; Conditions</a>for additional details.

** Fitter Law, or one of its contracted or affiliate law firm, will provide litigation services in one of the following ways: hourly, flat-fee, contingency, or hybrid (reduced fee + contingency).&nbsp; This service is decided on a case-by-case basis, at the law firm's (that is providing the litigation services) discretion.<a href="https://fitterlaw.com?ff_landing=14" role="button">Apply Now!</a><h3>Start with confidence</h3><h3>Grow with guidance</h3><h3>Fitter Law, LLC</h3>150 S. Wacker Drive, Suite 2400
Chicago, IL 60606<a href="https://fitterlaw.com?ff_landing=14" role="button">Apply Now!</a><h3>OUR PARTNERS</h3><figure><img src="https://fitterlaw.com/wp-content/uploads/2021/01/AWS_Activate-logo-colored.png" alt="AWS_Activate-logo-colored"></figure><figure><img src="https://fitterlaw.com/wp-content/uploads/2021/01/Stripe-logo-colored.png" alt="Stripe-logo-colored"></figure><figure><img src="https://fitterlaw.com/wp-content/uploads/2021/01/hubspot-logo-color.png" alt="hubspot-logo-color"></figure><figure><img src="https://fitterlaw.com/wp-content/uploads/2021/01/Airtable.png" alt="Airtable"></figure><figure><img src="https://fitterlaw.com/wp-content/uploads/2021/01/dialpad-768x432.jpg" alt="dialpad"></figure><figure><img src="https://fitterlaw.com/wp-content/uploads/2021/01/Pipe-logo-colored.png" alt="Pipe-logo-colored"></figure><figure><img src="https://fitterlaw.com/wp-content/uploads/2021/01/rippling-logo-colored-768x110.png" alt="rippling-logo-colored"></figure><figure><img src="https://fitterlaw.com/wp-content/uploads/2021/01/Deel-logo-colored.png" alt="Deel-logo-colored"></figure><figure><img src="https://fitterlaw.com/wp-content/uploads/2021/01/freshworks-logo-colored-1-p11fqks9rvfirt1p3vogxa6n1fqo2ozalmx4nnyw2k.png" alt="freshworks-logo-colored-1-p11fqks9rvfirt1p3vogxa6n1fqo2ozalmx4nnyw2k"></figure><figure><img src="https://fitterlaw.com/wp-content/uploads/2021/01/Zendesk-wordmark-768x158.png" alt="Zendesk-wordmark"></figure><figure><img src="https://fitterlaw.com/wp-content/uploads/2021/01/Embroker-logo-colored.png" alt="Embroker-logo-colored"></figure><figure><img src="https://fitterlaw.com/wp-content/uploads/2021/01/Vouch-logo-colored.png" alt="Vouch-logo-colored"></figure><figure><img src="https://fitterlaw.com/wp-content/uploads/2021/01/Pilot-logo-colored.png" alt="Pilot-logo-colored"></figure><figure><img src="https://fitterlaw.com/wp-content/uploads/2021/01/divvy_logo.png" alt="divvy_logo"></figure><figure><img src="https://fitterlaw.com/wp-content/uploads/2021/01/Lockup_Logo_Black-768x203.png" alt="Lockup_Logo_Black"></figure>Previous
Next

Â© All rights reserved

Fitter Law, LLC - Attorney Advertising` }} /&gt;</div>);
}</div></defaultlayout></body></html>