import Layout from '@/components/layouts/page-layout';

export default function illinois_local_counselPage() {
  return (
    <Layout>
      <div className="container mx-auto px-4 py-8">
        <h1 className="text-3xl font-bold mb-4">Illinois Local Counsel</h1>
        <div dangerouslySetInnerHTML={{ __html: $(@{ID=3828; post_author=1; post_date=2021-12-15 12:34:57; post_date_gmt=2021-12-15 18:34:57; post_content=<h1>Local Counsel Services</h1>		
		<p>To be compliant with the local rules of the United States District Court for the Northern District of Illinois in Chicago, out-of-state lawyers and law firms are required to designate local counsel.Â  Fitter Law assists such lawyers and firms in complying with the Local Rules.</p>		
			<h2>When Must a Firm Designate Local Counsel?</h2>		
		<p>In the Northern District of Illinois, the rules require non-resident attorneys to designate local counsel or risk substantial penalties:</p>		
												<img width="744" height="494" src="https://fitterlaw.com/wp-content/uploads/Litigation.webp" alt="Fitter Law Litigation Services" loading="lazy" srcset="https://i2.wp.com/fitterlaw.com/wp-content/uploads/Litigation.png?w=900&amp;ssl=1 900w, https://i2.wp.com/fitterlaw.com/wp-content/uploads/Litigation.png?resize=300%2C199&amp;ssl=1 300w, https://i2.wp.com/fitterlaw.com/wp-content/uploads/Litigation.png?resize=768%2C510&amp;ssl=1 768w" sizes="(max-width: 744px) 100vw, 744px" />														
		<blockquote><p style="text-align: left;"><strong>(a)Â Designation.Â </strong>An attorney not having an office within this District (â€œnonresident attorneyâ€) may appear before this Court only upon having designated as local counsel a member of the bar of this Court having an office within this District upon whom service of papers may be made...</p><p style="text-align: left;"><strong>(b) Penalties.Â </strong>Where a nonresident attorney tenders documents without the required designation of local counsel, the Clerk shall process them as if the designation were filed and shall promptly notify the attorney in writing that the designation must be made within 30 days. If the attorney fails to file the designation within that time, the documents filed by the attorney may be stricken by the court...</p><p style="text-align: left;"><strong>(c) Duties of Local Counsel... </strong>In emergencies, local counsel may appear on behalf of the nonresident attorney...</p><p style="text-align: right;">(United States District Court Northern District of Illinois. <a style="color: #0000ff;" href="https://www.ilnd.uscourts.gov/LocalRules.aspx?eFRCR82Cx5Y=" target="_blank" rel="noopener">Local Rule Â§83.15</a>. 2016)</p><p style="padding-left: 40px;">Â </p></blockquote><p>Collection firms, for example, use local counsel when they have multiple matters in outlying jurisdictions and no crucial decisions need to be made. The firms send local counsel to appear in status hearings, mediations, or motion hearings in foreclosure and small claims cases.</p><p>Personal injury firms also use coverage attorneys in status and motion hearings. Bankruptcy firms may need coverage for motion hearings or 341 meetings. On occasion, local counsel may be asked to file documents with a court. Majority of the legal services, such as depositions, negotiations, and trials, are still handled by the personal injury firms.</p><p>Local Counsel is the firm's temporary local representative.Â </p><p>Fitter Law's local counsel services in the Northern District of Illinois assist law firms that represent clients from around the world.</p><p>Attorneys can contact us at <a href="mailto:local.counsel@fitterlaw.com" target="_blank" rel="noopener">local.counsel@fitterlaw.com</a> or call <a href="tel:3127411073">(312) 741-1073</a></p>; post_title=Illinois Local Counsel; post_excerpt=; post_status=publish; comment_status=closed; ping_status=closed; post_password=; post_name=illinois-local-counsel; to_ping=; pinged=; post_modified=2024-09-30 02:09:34; post_modified_gmt=2024-09-30 07:09:34; post_content_filtered=; post_parent=13; guid=https://fitterlaw.com/?page_id=3828; menu_order=0; post_type=page; post_mime_type=; comment_count=0}.post_content -replace "'", "\'") }} />
      </div>
    </Layout>
  );
}
